title: "Blog by Herb Silverman"
description: "Notes on optimism, leadership, communication, and service."

minima:
  skin: classic
  custom_css:
    - /assets/css/custom.css

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - index.md
  - blog.md
  - about.md
  - contact.md
